import { GameConfig } from './types';

export const GAME_CONFIGS: Record<string, GameConfig> = {
  'helix-jump': {
    gameId: 'helix-jump',
    title: 'Helix Jump',
    titleAmharic: 'ሄሊክስ ጃምፕ',
    genre: '3D Arcade Physics',
    tagline: 'Rotate the helix tower to guide the bouncing ball through safe platforms!',
    description: 'High-octane 3D arcade drop. Spin the concentric helix tower left and right to allow the continuously bouncing ball to fall through gaps while dodging red hazard zones.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-amber-500 via-red-500 to-rose-700',
      accentColor: '#EF4444',
      badgeBg: 'bg-red-500/20 text-red-300 border-red-500/40',
      cardBg: 'bg-slate-900/90 border-red-500/30',
      iconEmoji: '🌀',
      bannerBg: 'bg-gradient-to-b from-red-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Rotate the helix cylinder so the bouncing ball drops down through open gaps without touching forbidden hazard sections.',
      rules: [
        'Swipe left or right to rotate the entire helix tower.',
        'The ball bounces automatically on normal platforms.',
        'Drop through gaps between platforms to descend.',
        'NEVER land on the bright hazard platforms—doing so will shatter the ball.',
        'Dropping through 3 or more platforms continuously charges a Fireball that smashes the next platform.',
      ],
      controls: 'Touch and drag horizontally across the screen to rotate the tower.',
      proTips: [
        'Build up a multi-floor speed drop to activate the invulnerable Fireball state.',
        'Look ahead below your current floor to align with the next gap.',
      ],
    },
    achievements: [
      { id: 'hj_drop_master', title: 'Tower Plunger', desc: 'Drop 5 floors in a single dive', icon: '⬇️', maxProgress: 5 },
      { id: 'hj_fireball', title: 'Fireball Breaker', desc: 'Smash a hazard platform with Fireball', icon: '🔥', maxProgress: 1 },
      { id: 'hj_tower_cleared', title: 'Helix Champion', desc: 'Complete 10 levels', icon: '🏆', maxProgress: 10 },
    ],
    about: {
      version: '3.2.0',
      developer: 'TelePlay Game Studios',
      engine: 'Three.js 60FPS Continuous Arcade Loop',
      features: ['Dynamic splash splatters', 'Procedural tower geometries', '40 skill stages'],
    },
  },

  'bubble-shooter': {
    gameId: 'bubble-shooter',
    title: 'Bubble Shooter',
    titleAmharic: 'ባብል ሹተር',
    genre: 'Arcade Bubble Match',
    tagline: 'Aim cannon and pop clusters of 3 or more matching bubbles!',
    description: 'Classic arcade bubble popping game with precision angle aiming, bouncy wall bank shots, and cascading ceiling drops.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-sky-500 via-blue-600 to-indigo-700',
      accentColor: '#38BDF8',
      badgeBg: 'bg-sky-500/20 text-sky-300 border-sky-500/40',
      cardBg: 'bg-slate-900/90 border-sky-500/30',
      iconEmoji: '🫧',
      bannerBg: 'bg-gradient-to-b from-sky-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Launch colored bubbles at the suspended ceiling cluster to form groups of 3 or more matching colors.',
      rules: [
        'Aim the cannon using the laser trajectory guideline.',
        'Release to shoot the current projectile bubble.',
        'Matching 3 or more bubbles of identical color will pop them.',
        'Any disconnected bubbles suspended below the popped group will drop and grant bonus points.',
        'Clear all bubbles before they descend below the danger threshold line.',
      ],
      controls: 'Touch and drag on screen to aim, release your finger to fire.',
      proTips: [
        'Bank shots off the side walls to reach tricky clusters high up.',
        'Target root attachments: dropping a cluster yields much more score than popping individually.',
      ],
    },
    achievements: [
      { id: 'bs_popper', title: 'Bubble Popper', desc: 'Pop 50 bubbles', icon: '🫧', maxProgress: 50 },
      { id: 'bs_avalanche', title: 'Bubble Avalanche', desc: 'Drop 10 bubbles in one shot', icon: '🏔️', maxProgress: 10 },
      { id: 'bs_sniper', title: 'Precision Gunner', desc: 'Clear 5 levels with no missed shots', icon: '🎯', maxProgress: 5 },
    ],
    about: {
      version: '2.3.0',
      developer: 'TelePlay Game Studios',
      engine: 'Hexagonal Grid Trajectory Physics',
      features: ['Accurate laser bounce physics', 'Next bubble switcher', '40 challenging layouts'],
    },
  },

  'emoji-iq': {
    gameId: 'emoji-iq',
    title: 'EMOJI IQ',
    titleAmharic: 'ኢሞጂ አይኪው',
    genre: 'Tournament Emoji & Number Calculation Challenge',
    tagline: 'Master 40 stages of emoji equations, logical calculations & tournament scoring!',
    description: 'Solve 12 unique emoji equation puzzle categories across 40 progressive stages with multi-step calculations, order of operations, changed quantities, visual differences, combos, hints, lives, store, and competitive leaderboard.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-violet-600 via-indigo-600 to-cyan-700',
      accentColor: '#6C5CE7',
      badgeBg: 'bg-violet-500/20 text-violet-300 border-violet-500/40',
      cardBg: 'bg-slate-900/90 border-violet-500/30',
      iconEmoji: '🧠',
      bannerBg: 'bg-gradient-to-b from-[#241F3D] via-violet-950/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Deduce emoji values from clue equations, apply PEMDAS operations, and select the correct numerical answer.',
      rules: [
        'Deduce the numerical values of emojis from the clue equations.',
        'Mind the order of operations: multiplication and division are done before addition and subtraction.',
        'Watch for emoji quantity changes (e.g. triple bananas vs single banana).',
        'Speed and consecutive correct answers increase your combo multiplier.',
        'Use hints to eliminate wrong options if you need help.',
      ],
      controls: 'Tap the correct numerical answer tile.',
      proTips: [
        'Always check the operation signs in the target equation carefully (watch for × vs +).',
        'Solve row by row from top to bottom.',
      ],
    },
    achievements: [
      { id: 'eiq_first_solve', title: 'First Equation', desc: 'Solve your first Emoji IQ puzzle', icon: '🧠', maxProgress: 1 },
      { id: 'eiq_perfect_combo', title: 'Calculation Master', desc: 'Achieve a 5x combo streak', icon: '⚡', maxProgress: 5 },
      { id: 'eiq_tournament_champ', title: 'IQ Grandmaster', desc: 'Complete all 40 tournament stages', icon: '👑', maxProgress: 40 },
    ],
    about: {
      version: '1.0.0',
      developer: 'GameON Studios',
      engine: 'Deterministic Emoji Arithmetic & Logic Engine',
      features: ['40 Progressive Stages', '12 Unique Mathematical Categories', 'Tournament Skill Scoring & Combos', 'Persistent Global Standings'],
    },
  },

  'royal-water-sort': {
    gameId: 'royal-water-sort',
    title: 'Royal Water Sorting',
    titleAmharic: 'ሮያል ወተር ሶርት',
    genre: '3D Liquid Puzzle',
    tagline: 'Pour majestic colored liquids into royal glass vials to complete sorting!',
    description: 'Luxurious 3D liquid sorting game with crystalline flasks. Pour vibrant royal potions between vials until each container holds a single uniform color.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'stage',
    scoreLabel: 'LEVEL',
    theme: {
      primaryGradient: 'from-blue-600 via-indigo-600 to-purple-800',
      accentColor: '#38BDF8',
      badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
      cardBg: 'bg-slate-900/90 border-blue-500/30',
      iconEmoji: '🧪',
      bannerBg: 'bg-gradient-to-b from-blue-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Transfer liquid layers between glass vials so each vial holds only one pure color.',
      rules: [
        'Tap a vial to pick it up.',
        'Tap another vial to pour the top liquid layer into it.',
        'You can only pour liquid into another vial if the top colors match and there is room.',
        'An empty vial can hold any liquid color.',
        'Use the Undo button to step back if you make a mistake.',
      ],
      controls: 'Tap a vial to select, then tap target vial to pour.',
      proTips: [
        'Always try to uncover trapped bottom colors as soon as possible.',
        'Keep at least one vial empty as a temporary buffer for sorting.',
      ],
    },
    achievements: [
      { id: 'rws_first_potion', title: 'Alchemist', desc: 'Sort your first royal vial', icon: '👑', maxProgress: 1 },
      { id: 'rws_perfect_pour', title: 'Royal Scholar', desc: 'Complete 5 levels without undo', icon: '✨', maxProgress: 5 },
      { id: 'rws_crown_master', title: 'Vial Monarch', desc: 'Clear Level 20', icon: '🏆', maxProgress: 20 },
    ],
    about: {
      version: '3.0.0',
      developer: 'TelePlay Game Studios',
      engine: '3D Liquid Shader Simulation',
      features: ['Realistic fluid pouring physics', 'Crystalline glass reflections', '40 championship puzzles'],
    },
  },

  'hill-rider': {
    gameId: 'hill-rider',
    title: 'Hill Climb',
    titleAmharic: 'ሂል ክላይምብ',
    genre: '2.5D Physics Racing',
    tagline: 'Balance throttle and brake to conquer rugged mountain terrain!',
    description: 'Realistic vehicle physics racer. Drive custom jeeps and monster trucks over steep undulating hills, collect fuel canisters, and perform airborne flips.',
    hasLevels: false,
    scoreType: 'score',
    scoreLabel: 'METERS',
    theme: {
      primaryGradient: 'from-lime-600 via-emerald-600 to-green-800',
      accentColor: '#84CC16',
      badgeBg: 'bg-lime-500/20 text-lime-300 border-lime-500/40',
      cardBg: 'bg-slate-900/90 border-lime-500/30',
      iconEmoji: '🚙',
      bannerBg: 'bg-gradient-to-b from-green-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Drive as far as possible across steep hills without running out of gas or flipping your vehicle.',
      rules: [
        'Hold Gas (right pedal) to accelerate forward.',
        'Hold Brake (left pedal) to decelerate or tilt backwards in mid-air.',
        'Balance your vehicle in mid-air to land parallel with the sloped ground.',
        'Collect red Gas Cans along the route to keep your fuel gauge full.',
        'If your driver strikes the ground or fuel empties, your run ends.',
      ],
      controls: 'Use the on-screen Gas and Brake pedals or Left/Right Arrow keys.',
      proTips: [
        'Feather the throttle over steep crests so you don\'t flip backwards.',
        'Airborne flips award extra coin bonuses, but ensure a smooth wheels-down landing.',
      ],
    },
    achievements: [
      { id: 'hr_100m', title: 'Off-Roader', desc: 'Reach 200 meters', icon: '🏁', maxProgress: 200 },
      { id: 'hr_backflip', title: 'Airborne Daredevil', desc: 'Land a full mid-air flip', icon: '🤸', maxProgress: 1 },
      { id: 'hr_1000m', title: 'Mountain Legend', desc: 'Conquer 1,000 meters in a single run', icon: '🏔️', maxProgress: 1000 },
    ],
    about: {
      version: '2.4.0',
      developer: 'TelePlay Game Studios',
      engine: 'Three.js 2.5D Rigid Body Simulation',
      features: ['Dynamic suspension springs', 'Continuous procedural hills', 'Fuel economy challenge'],
    },
  },

  'sorting-balls': {
    gameId: 'sorting-balls',
    title: 'Sorting Ball',
    titleAmharic: 'ሶርቲንግ ቦልስ',
    genre: 'Color Sorting Puzzle',
    tagline: 'Sort vibrant colored 3D spheres into matching test tubes!',
    description: 'Challenging logic puzzle with 3D glass tubes. Transfer top balls between flasks until every tube contains only one uniform color.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'stage',
    scoreLabel: 'STAGE',
    theme: {
      primaryGradient: 'from-violet-600 via-indigo-600 to-purple-800',
      accentColor: '#8B5CF6',
      badgeBg: 'bg-violet-500/20 text-violet-300 border-violet-500/40',
      cardBg: 'bg-slate-900/90 border-violet-500/30',
      iconEmoji: '🧪',
      bannerBg: 'bg-gradient-to-b from-indigo-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Pour balls between glass tubes so that all balls of the same color are grouped together in their own tube.',
      rules: [
        'Tap a tube to lift its top ball(s).',
        'Tap another tube to pour the ball into it.',
        'You can only pour a ball on top of another ball of the same color.',
        'A tube can hold at most 4 balls.',
        'An empty tube can accept any color ball.',
        'Level is won when all tubes either contain 4 balls of the same color or are completely empty.',
      ],
      controls: 'Tap on a tube to select, then tap target tube to transfer.',
      proTips: [
        'Use empty tubes wisely as temporary parking spots for blocked colors.',
        'Look ahead: clear one color entirely to free up a permanent sorting tube.',
      ],
    },
    achievements: [
      { id: 'sb_first_sort', title: 'Lab Assistant', desc: 'Sort your first tube', icon: '🧪', maxProgress: 1 },
      { id: 'sb_perfect_sort', title: 'Master Chemist', desc: 'Complete 5 levels with 3 stars', icon: '🌟', maxProgress: 5 },
      { id: 'sb_puzzle_genius', title: 'Color Prodigy', desc: 'Solve Level 20', icon: '🎓', maxProgress: 20 },
    ],
    about: {
      version: '2.8.0',
      developer: 'TelePlay Game Studios',
      engine: 'Three.js 3D Realistic Shader Engine',
      features: ['Realistic glass refraction', 'Coordinated multi-ball pours', 'Undo & extra tube powerups'],
    },
  },

  'puzzle-block': {
    gameId: 'puzzle-block',
    title: 'Block',
    titleAmharic: 'ፓዝል ብሎክ',
    genre: 'Grid Block Puzzle',
    tagline: 'Fit wooden and jewel shapes on the 10x10 board to clear rows and columns!',
    description: 'Strategic block placement game on a clean 10x10 board. Clear full horizontal lines and vertical columns to keep the board clear.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-amber-600 via-yellow-600 to-orange-700',
      accentColor: '#D97706',
      badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
      cardBg: 'bg-slate-900/90 border-amber-500/30',
      iconEmoji: '🧱',
      bannerBg: 'bg-gradient-to-b from-amber-950/70 via-stone-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Place 3 provided polyomino block pieces onto the 10x10 board. Fill full rows or columns to clear them and score points.',
      rules: [
        'Drag pieces from the tray onto the 10x10 board.',
        'Blocks cannot overlap and cannot be rotated.',
        'Complete a full horizontal row or vertical column of 10 blocks to clear it.',
        'Clearing multiple rows/columns simultaneously triggers mega combo bonuses.',
        'Game is over when there is no room left on the board for any of the 3 pieces.',
      ],
      controls: 'Touch and drag a piece onto any valid empty cells on the board.',
      proTips: [
        'Always maintain space for the large 3x3 square and 5-block long lines.',
        'Avoid creating isolated 1-cell gaps that are hard to fill.',
      ],
    },
    achievements: [
      { id: 'pb_first_clear', title: 'Clear Builder', desc: 'Clear your first line', icon: '🪵', maxProgress: 1 },
      { id: 'pb_triple_clear', title: 'Combo Master', desc: 'Clear 3 lines in one placement', icon: '💥', maxProgress: 1 },
      { id: 'pb_high_score', title: 'Block Legend', desc: 'Score over 2,000 points', icon: '🏆', maxProgress: 2000 },
    ],
    about: {
      version: '3.0.0',
      developer: 'TelePlay Game Studios',
      engine: 'High-Precision 10x10 Matrix Engine',
      features: ['Clean empty board initialization', '40 tournament stages', 'Real-time score persistence'],
    },
  },

  'memory-match': {
    gameId: 'memory-match',
    title: 'Memory Match',
    titleAmharic: 'ሜሞሪ ማች',
    genre: 'Brain & Memory',
    tagline: 'Flip cards, memorize positions, and match twin pairs!',
    description: 'Sharpen your cognitive memory and concentration. Flip cards two at a time to uncover matching cultural and safari icons before the clock expires.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-teal-500 via-cyan-600 to-blue-700',
      accentColor: '#14B8A6',
      badgeBg: 'bg-teal-500/20 text-teal-300 border-teal-500/40',
      cardBg: 'bg-slate-900/90 border-teal-500/30',
      iconEmoji: '🃏',
      bannerBg: 'bg-gradient-to-b from-teal-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Find all matching pairs of cards on the board in the fewest turns and fastest time.',
      rules: [
        'Tap any card to flip it face up.',
        'Tap a second card to see if it matches the first.',
        'If the cards match, they stay revealed and you earn combo score.',
        'If they do not match, they flip back face down after a brief glance.',
        'Match all pairs on the board to complete the level.',
      ],
      controls: 'Tap cards to flip them.',
      proTips: [
        'Establish a mental grid pattern (scan top row left to right).',
        'Maintain a steady pace to keep your streak bonus multiplier active.',
      ],
    },
    achievements: [
      { id: 'mm_quick_pair', title: 'Sharp Eye', desc: 'Find 5 pairs in under 15 seconds', icon: '👀', maxProgress: 5 },
      { id: 'mm_perfect', title: 'Photographic Memory', desc: 'Complete a level without any wrong flip', icon: '🧠', maxProgress: 1 },
      { id: 'mm_safari_king', title: 'Memory Champ', desc: 'Clear Level 15', icon: '🦁', maxProgress: 15 },
    ],
    about: {
      version: '2.1.0',
      developer: 'TelePlay Game Studios',
      engine: 'Card Flip 3D Matrix',
      features: ['Ethiopian wildlife icons', 'Combo streak multipliers', '40 mental difficulty levels'],
    },
  },

  'color-rush': {
    gameId: 'color-rush',
    title: 'Color Rush',
    titleAmharic: 'ከለር ረሽ',
    genre: 'Fast Reaction',
    tagline: 'Match the target color with lightning-fast tap reflexes!',
    description: 'High-speed cognitive reflex challenge across 10 progressive rounds. Match the central vibrant target color against a grid of choices with sub-16ms touch response.',
    hasLevels: true,
    totalLevels: 10,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-yellow-500 via-amber-500 to-orange-600',
      accentColor: '#F59E0B',
      badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
      cardBg: 'bg-slate-900/90 border-amber-500/30',
      iconEmoji: '⚡',
      bannerBg: 'bg-gradient-to-b from-amber-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Identify the large central target color and tap its exact match on the choice grid as fast as possible.',
      rules: [
        'Observe the central target color swatch and its chromatic label.',
        'Tap the matching color swatch from the bottom options grid.',
        'Correct selections advance to the next round immediately and reward time bonus points.',
        'Incorrect taps penalize your combo streak and time.',
        'Complete all 10 rounds to achieve the maximum 400 tournament points.',
      ],
      controls: 'Tap the matching color tile.',
      proTips: [
        'Do not read the color name text if it conflicts—focus on the actual visual hue!',
        'Speed is rewarded: faster taps yield up to 15 bonus points per round.',
      ],
    },
    achievements: [
      { id: 'cr_fast_tap', title: 'Lightning Tap', desc: 'Answer a round in under 0.5s', icon: '⚡', maxProgress: 1 },
      { id: 'cr_perfect_10', title: 'Flawless Rush', desc: 'Clear all 10 rounds with 100% accuracy', icon: '🎯', maxProgress: 1 },
      { id: 'cr_400_club', title: '400 PTS Elite', desc: 'Achieve the maximum 400 points', icon: '👑', maxProgress: 400 },
    ],
    about: {
      version: '1.9.0',
      developer: 'TelePlay Game Studios',
      engine: 'High-Speed Reflex Dispatcher',
      features: ['Sub-16ms latency', '10 progressive rounds', 'Normalized 400 PTS tournament model'],
    },
  },

  'solitaire': {
    gameId: 'solitaire',
    title: 'Solitaire',
    titleAmharic: 'ሶሊቴር',
    genre: 'Classic Card',
    tagline: 'Timeless Klondike Solitaire with smooth card deals and smart hints!',
    description: 'Play the world-renowned Klondike Solitaire card game. Stack tableau columns in descending order with alternating red and black suits.',
    hasLevels: false,
    scoreType: 'score',
    scoreLabel: 'SCORE',
    theme: {
      primaryGradient: 'from-emerald-700 via-green-800 to-teal-900',
      accentColor: '#059669',
      badgeBg: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
      cardBg: 'bg-slate-900/90 border-emerald-500/30',
      iconEmoji: '♠️',
      bannerBg: 'bg-gradient-to-b from-emerald-950/80 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Organize a standard 52-card deck into the 4 foundation piles from Ace up to King by suit.',
      rules: [
        'Build foundations up from Ace to King (A, 2, 3... Q, K) sorted by suit.',
        'Build tableau columns down in descending rank with alternating red and black colors.',
        'Only Kings can be placed into empty tableau spaces.',
        'Draw cards from the stockpile when no tableau moves are available.',
      ],
      controls: 'Tap a card to auto-move it to the best available position, or drag and drop onto a column.',
      proTips: [
        'Always uncover face-down tableau cards first before drawing from the stock.',
        'Do not empty a tableau column unless you have a King ready to occupy it.',
      ],
    },
    achievements: [
      { id: 'sol_first_win', title: 'Card Shark', desc: 'Win your first Solitaire deal', icon: '🃏', maxProgress: 1 },
      { id: 'sol_speed_deal', title: 'Lightning Hands', desc: 'Finish a deal in under 3 minutes', icon: '⏱️', maxProgress: 1 },
      { id: 'sol_streak_3', title: 'Triple Crown', desc: 'Win 3 deals in a row', icon: '👑', maxProgress: 3 },
    ],
    about: {
      version: '2.5.0',
      developer: 'TelePlay Game Studios',
      engine: 'CardCanvas 2D Physics',
      features: ['Solvable deal algorithm', 'Unlimited undo & auto-hints', 'Vegas and Standard scoring'],
    },
  },

  'emoji-sorting-ball': {
    gameId: 'emoji-sorting-ball',
    title: 'EMOJI SORTING BALL',
    titleAmharic: 'ኢሞጂ ሶርቲንግ ቦል',
    genre: '3D Emoji Sorting Tournament Puzzle',
    tagline: 'Sort stylized 3D emoji vinyl spheres into color-coded crystal tubes across 40 levels!',
    description: 'The premier 3D Emoji Sorting tournament challenge. Transfer identical emoji spheres between vibrant tubes, utilize sequential multi-ball transfers, manage undos, hints, and buffer tubes, and maximize your tournament par efficiency.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'stage',
    scoreLabel: 'LEVEL',
    theme: {
      primaryGradient: 'from-violet-600 via-fuchsia-600 to-pink-600',
      accentColor: '#8B5CF6',
      badgeBg: 'bg-violet-500/20 text-violet-300 border-violet-500/40',
      cardBg: 'bg-slate-900/90 border-violet-500/30',
      iconEmoji: '😀',
      bannerBg: 'bg-gradient-to-b from-purple-950/70 via-slate-900/60 to-slate-950',
    },
    howToPlay: {
      summary: 'Sort matching 3D emoji spheres into designated color-coded crystal tubes until every tube is solved.',
      rules: [
        'Tap a tube to lift its top emoji sphere (or contiguous matching group).',
        'Tap another tube to transfer the emoji spheres into it.',
        'Spheres can only be transferred into an empty tube or onto a matching emoji type.',
        'Each tube holds up to 4 emoji spheres.',
        'Solve all tubes with 4 matching emojis to complete the level and claim tournament bonuses.',
      ],
      controls: 'Tap on a tube to select, then tap destination tube to transfer.',
      proTips: [
        'Matching contiguous emojis lift and move together in a multi-ball wave.',
        'Aim to beat the Par move count for 3 stars and maximum tournament score.',
        'Use extra tubes or undo if you reach a dead end.',
      ],
    },
    achievements: [
      { id: 'esb_first_level', title: 'First Emoji Sort', desc: 'Complete your first Emoji Sorting level', icon: '😀', maxProgress: 1 },
      { id: 'esb_star_sorter', title: 'Emoji Virtuoso', desc: 'Achieve 3 stars on 10 levels', icon: '🌟', maxProgress: 10 },
      { id: 'esb_master_mind', title: 'Grand Emoji Master', desc: 'Complete all 40 tournament levels', icon: '👑', maxProgress: 40 },
    ],
    about: {
      version: '1.0.0',
      developer: 'GameON Studios',
      engine: 'Three.js 3D Vinyl Sphere Engine',
      features: ['Stylized 3D vinyl emoji spheres', 'Mandatory 8-tube vibrant palette', '40 isomorphic tournament levels', 'Undo, Hint, and Extra Buffer Tubes'],
    },
  },

  'flip-tile': {
    gameId: 'flip-tile',
    title: 'Flip Tile',
    titleAmharic: 'ፍሊፕ ታይል',
    genre: 'Memory Duel',
    tagline: 'Flip matching tiles, outsmart the AI opponent, and conquer 40 tournament levels!',
    description: 'Turn-based tile memory duel featuring 40 handcrafted tournament stages with strategic AI bot, dynamic board palettes, and progressive difficulty.',
    hasLevels: true,
    totalLevels: 40,
    scoreType: 'score',
    scoreLabel: 'PTS',
    theme: {
      primaryGradient: 'from-amber-500 via-yellow-400 to-amber-600',
      accentColor: '#F5A623',
      badgeBg: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
      cardBg: 'bg-slate-900/90 border-amber-500/30',
      iconEmoji: '🃏',
      bannerBg: 'bg-gradient-to-b from-purple-950/70 via-slate-900 to-black',
    },
    howToPlay: {
      summary: 'Take turns flipping 2 tiles at a time to find matching pairs against an AI bot. Matching pairs vanish and grant bonus turns.',
      rules: [
        'Tap any face-down tile to flip and reveal its icon.',
        'Match 2 identical icons to claim the pair and remove them from the board.',
        'Claiming a pair gives you an immediate extra turn.',
        'Mismatched tiles flip back face-down, passing the turn to the Bot.',
        'The player with the most matching pairs when the board clears wins the stage.',
      ],
      controls: 'Tap any face-down tile to flip. 100% mobile touch and desktop mouse responsive.',
      proTips: [
        'Pay close attention during the Bot turn to memorize tile locations.',
        'At higher stages, the Bot has near-photographic memory — avoid making blind guesses when pairs are already exposed.',
      ],
    },
    achievements: [
      { id: 'ft_first_stage', title: 'Tile Flipper', desc: 'Win Stage 1 of Flip Tile', icon: '🏁', maxProgress: 1 },
      { id: 'ft_streak_10', title: 'Memory Master', desc: 'Conquer 10 tournament stages', icon: '⚡', maxProgress: 10 },
      { id: 'ft_grand_champ', title: 'Flip Tile Legend', desc: 'Conquer all 40 tournament stages', icon: '👑', maxProgress: 40 },
    ],
    about: {
      version: '1.0.0',
      developer: 'TelePlay Game Studios',
      engine: 'HTML5 3D Transform Tile Engine',
      features: ['40 Handcrafted Stages', 'Competitive Strategic AI', 'Real Stage Progression Locking', 'Web Audio Synthesizer'],
    },
  },
};

export const getGameConfig = (gameId: string): GameConfig => {
  return (
    GAME_CONFIGS[gameId] || {
      gameId,
      title: gameId.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()),
      titleAmharic: 'ጨዋታ',
      genre: 'Arcade Game',
      tagline: 'Play and compete for tournament glory!',
      description: 'Engaging tournament game with full leaderboard tracking and skill challenges.',
      hasLevels: true,
      totalLevels: 40,
      scoreType: 'score',
      scoreLabel: 'PTS',
      theme: {
        primaryGradient: 'from-blue-600 via-indigo-600 to-purple-700',
        accentColor: '#3B82F6',
        badgeBg: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
        cardBg: 'bg-slate-900/90 border-blue-500/30',
        iconEmoji: '🎮',
      },
      howToPlay: {
        summary: 'Follow the on-screen objective to clear levels and achieve high scores.',
        rules: ['Tap or swipe to control gameplay.', 'Reach the target score to clear each stage.'],
        controls: 'Touch screen or use keyboard controls.',
        proTips: ['Practice regularly to master the mechanics.'],
      },
      achievements: [
        { id: 'default_play', title: 'First Game', desc: 'Play your first match', icon: '🎮', maxProgress: 1 },
      ],
      about: {
        version: '1.0.0',
        developer: 'TelePlay Game Studios',
        engine: 'Web Canvas Engine',
        features: ['Leaderboard integration', 'Offline progress tracking'],
      },
    }
  );
};
